version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "4003:4002"
    environment:
      SQL_SERVER_USER: tu_usuario
      SQL_SERVER_PASSWORD: tu_contraseña
      SQL_SERVER_HOST: tu_host
      SQL_SERVER_DATABASE: tu_base_de_datos
